# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation:even
newer tools like Pandas(Chapter03)are built around the NumPy array. This section will
present several examples of using NumPy array  manipulation to access data and subarrays, and
to split, reshape, and join the arrays. While the types of operations shown here may 
seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout
the book.Get to know them well! 

We`ll cover a few categories of basic array manipulations here:
    ·Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
    ·Indexing of arrays: Getting and setting the value of individual array elements
    ·Slicing of arrays: Getting and setting smaller subarrays within a larger array
    ·Reshaping of arrays: Changing the shape of a given array
    ·Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many


# NumPy Array Attributes

First let's discuss some useful array attributes.We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.We'll use NumPy's random number enerator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [1]:
import numpy as np
np.random.seed(0)    # seed for reproducibility

x1 = np.random.randint(10, size=6)   # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ndim(the number of dimensions), shape(the size of each dimension), 
and size(the total size of array):


In [2]:
print("x3 ndim: " , x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


Another useful attribute is the dtype, the data type of the array(which we discussed 
previously in Understanding Data Types in Python):

In [3]:
print("dtype:", x3.dtype)

dtype: int32


In [4]:
print("intemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

intemsize: 4 bytes
nbytes: 240 bytes


# Array Indexing: Accessing Single Elements

If you are familiar with Python`s standard list indexing, indexing in NumPy will quite
familiar.In a one-dimensional array, the ith value(counting from zero) can be accessed by
specifying the desired index in square brackets, just as with Python lists:

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[4]

7

In [8]:
x1[-1]

9

In [9]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[0, 0]

3

In [12]:
x2[2, 0]

1

In [13]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [15]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.This means, for
example, that if you attempt to insert a floating-point to an integer array, the value will
be silently truncated.Dont`t be caught unaware by this behavior!

In [16]:
x1[0] = 3.14159     # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays

Just as wee can use square brackets to access individual array elements, we can also use them
to access subarrays with the slice notation, marked by the colon(:)character. The NumPy slicing
syntax following that of the standard Python list;to access a slice of an array x, use this:
    
    x[start:stop:step]
    
If any of these are unspecified, they default to the values start=0, stop=size of dimension, 
step=1. We`ll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

# One-dimensional subarrays

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[:5]    # first five elements

array([0, 1, 2, 3, 4])

In [19]:
x[5:]   # elements after index 5

array([5, 6, 7, 8, 9])

In [20]:
x[4:7]     # middle sub-array

array([4, 5, 6])

In [21]:
x[::2]    # every other element

array([0, 2, 4, 6, 8])

In [22]:
x[1::2]   # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and 
stop are swapped.This becomes a convenient way to reverse an array:

In [23]:
x[::-1]   # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
x[5::2]    # reversed every other from index 5

array([5, 7, 9])

# Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [25]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [26]:
x2[:2, :3]     # two rows, three colums

array([[12,  5,  2],
       [ 7,  6,  8]])

In [27]:
x2[:3, ::2]    # all rows, every other colum

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensional can even be reversed together:

In [28]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

# Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.This can 
be done by combining indexing and slicing, using an empty slice marked by a single colon(:):

In [29]:
print(x2[:, 0])        # first column of x2

[12  7  1]


In [30]:
print(x2[0, :])       # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more syntax:

In [31]:
print(x2[0])        # equivalent to x2[0, :]

[12  5  2  4]


# Subarrays as no-copy views

One important-and extremely useful-thing to know about array slices is that they return
views rather than copies of the array data. This one area in which NumPy array slicing differs
from Python list slicing: in lists, slices will be copies.Consider our two-dimensional array
from before:

In [32]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let`s extract a 2 x 2 subarray from this:

In [33]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we`ll see that the orginal array is changed! Observe:

In [34]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [35]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
