# Aggregations: Min, Max, and Everything In Between


Often when faced with a large amount of data, a first step is to compute summary statistics 
for the data in question.Perhaps the most common summary statistics are the mean and 
standard deviation, which allow you to summarize the "typical" values in a dataset, but other
aggregates are useful as well(the sum, product, median, minimum and maximum, quantiles, 
    etc.)
NumPy has fast built-aggregation functions for working on arrays; we`ll discuss and 
demonstrate some of them here.

# Summing the values in an Array

As a quick example, consider computing the sum of all values in an array. Python itself can
do this using the built-in sum function:

In [3]:
import numpy as np

In [4]:
L = np.random.random(100)
sum(L)

52.10252724046464

The synatax is quite similar to that of NumPy`s sum function, and the result is the same
in the simplest case:

In [5]:
np.sum(L)

52.10252724046465

However, because it executes the operation in compiled code, NumPy`s version of the operation
is computed much more quickly:

In [ ]:
big_array = np.random.rand(100000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

Be careful, though: the sum function and the np.sum function are not identical, which can
    sometimes lead to confusion! in particular, their optional arguments have different meanings,
    and  np.sum is aware of multiple array dimensions, as we will see in the following section.

# Minimum and Maximum

Similarly, Python has built-in min and max functions, used to find the minimum value and 
maxmum value of any given array:

In [1]:
min(big_array), max(big_array)

NameError: name 'big_array' is not defined

In [ ]:
NumPy`s corresponding functions have similar syntax, and again operate much more quickly:


In [11]:
np.min(big_array), np.max(big_array)

(1.2903421664489656e-09, 0.9999999995546099)

In [12]:
%timeit min(big_array)
%timeit np.min(big_array)

18 s ± 2.37 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
67.2 ms ± 997 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


For min, max, sum, and serveral other NumPy aggregates, a shorter syntax is to use methods
of the array object itself:

In [13]:
print(big_array.min(), big_array.max(), big_array.sum())

2.368959584053698e-09 0.9999999634568953 49999478.19046139


Whenever possible, make sure that you are using the NumPy version of these aggregates
when operating on  NumPy arrays!

# Multi dimensional aggregates

In [ ]:
One common type aggregation operation is an aggregate along a row or column. Say you have
some data stored in a two-dimensional array:

In [15]:
M = np.random.random((3, 4))
print(M)

[[0.88359075 0.64054968 0.88561576 0.46330575]
 [0.69049776 0.00095586 0.92388192 0.72232096]
 [0.21949018 0.47400658 0.21109168 0.87518646]]


In [16]:
M.sum()

6.990493336564891

In [ ]:
Aggregation functions take an additional argument specifying the axis along which the aggregate
is computed. For example, we can find the minimum value within each column by specifying axis = 0:

In [17]:
M.min(axis = 0)

array([0.21949018, 0.00095586, 0.21109168, 0.46330575])

In [ ]:
The function returns for values, corresponding to the four columns of numbers.
Similarly, we can find the maximum value within each row:

In [18]:
M.max(axis = 1)

array([0.88561576, 0.92388192, 0.87518646])

The way the axis is specified here can be confusing to users coming from other languages.
The axis keyword specifies the dimension of the array that will be collapsed, rather than
the dimension that will be returned. So specifying axis= 0 means that the first axis will
be collapsed: for two-dimensional arrays, this means values within each column will be 
aggregated.    

# Other aggregation functions

NumPy provides many other aggregation functions, but we won`t discuss them in detail
here.Additionally, most aggregates have a NaN-safe counterpart that computes the result
while ignoring missing values, which are marked by the special IEEE floating -point NaN
value(for a fuller discussion of missing data, seeHandiling Missing Data).Some of these
NaN-safe functions were not added until NumPy 1.8, so they will not be available in older
NumPy versions.

The following table provides a list of useful aggregation functions available in NumPy:
    
     Function Name        NaN-safe   Version          Description
   ----------------------------------------------------------------------
        np.sum             np.nansum             Compute sum of elements
        np.prod            np.nanprod             Compute  product  of elements
        np.mean            np.nanmean            Compute mean  of elements
        np.std             np.nanstd             Compute  standard  deviation
        np.var             np.nanvar             Compute variance
        np.min             np.nanmin             Find minimum value
        np.max             np.nanmax             Find  maximum  value
        np.argmin          np.nanmin             Find index of minimum value
        np.argmax          np.nanarmax           Find index of maximum value
        np.median          np.nanmedian          Compute median of elements
        np.percentile      np.nanpercentile      Compute rank-based statistics of elements
        np.any             N/A                   Evaluate whether any elements are true
        np.all             N/A                   Evaluate whether all elements are true
    
    We will see these aggregates often throughout the rest of the book.
    

# Example: What is the Average Height of US Presidents?

In [ ]:
Aggregates available in NumPy can be extremely useful for summarizing a set of values.
As a simple example, let`s consider the heights of all US presidents.This data is available
in the file president heights.csv, which is a simple comma-separated list of labels and 
values:

In [19]:
!head -4 data/president_heights.csv

'head' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [22]:
import pandas as pd
data = pd.read_csv('D:/Coding/Coding/1.Python-learning/Python-Excel/Packages/Python-Data-Science/data/data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

FileNotFoundError: File b'D:/Coding/Coding/1.Python-learning/Python-Excel/Packages/Python-Data-Science/data/data/president_heights.csv' does not exist