In [ ]:
# 理解python中的数据类型

In [ ]:
## python列表 不仅仅是一个列表

In [ ]:
创建一个整型值列表

In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [ ]:
或者创建一个字符串列表：

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(L2[0])

str

In [ ]:
因为python的动态类型特性，甚至可以创建一个异构的列表：

In [5]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
上述输出分别打印了四种不同的是数据类型：
- 1.bool：布尔值
- 2.str:字符串类型
- 3.float:带小数点的数据类型
- 4.int: 整数的数据类型

In [ ]:
## python中的固定类型数组

In [ ]:
内置的数组array模块可以用于创建统一类型的密集数组：

In [6]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
这里的'i'是一个数据类型码，表示数据为整型。

In [ ]:
## 从python列表创建数组

In [ ]:
首先，可以用np.array从python列表创建数组

In [8]:
# 整型数组
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
整型被转换为浮点型

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
不同于python列表，numpy数组可以被指定为多维的。以下是用列表的列表初始化多维数组的一种方法：

In [11]:
# 嵌套列表构成的多维数组
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
## 从头创建数组

In [12]:
# 创建一个长度为10的数组，数组的值都是0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# 创建一个3*5的浮点型数组，数组的值都是1
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# 创建一个9*9的浮点型数组，数组的值都是9
np.ones((9, 9), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
# 创建一个3*5的浮点数组，数组的值都是3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# 创建一个8*9的浮点数组，数组的值都是0.618
np.full((8, 9), 0.618)

array([[0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618],
       [0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618],
       [0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618],
       [0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618],
       [0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618],
       [0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618],
       [0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618],
       [0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618, 0.618]])

In [ ]:
### 创建一个线性序列数组

In [ ]:
#### 创建一个从0开始，到20结束，步长为2的线性序列数组

In [19]:
# 从0开始，到20结束，步长为2
# (它和内置的range()函数类似)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#### 创建一个从0开始，到100结束，步长为3的线性序列数组

In [20]:
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
#### 创建一个从0开始，到100结束，步长为5的线性序列数组

In [21]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
#### 创建一个5个元素的数组，这5个数均匀地分配到0~1

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#### 创建一个3*3的、在0~1均匀分布的随机数组成的数组

In [23]:
np.random.random((3, 3))

array([[0.57855566, 0.36999472, 0.60119379],
       [0.41658575, 0.61766138, 0.26393532],
       [0.54809953, 0.61825644, 0.56694456]])

In [ ]:
#### 创建一个3*3的、均值为0，标准差为1的正态分布的随机数数组

In [24]:
np.random.normal(0, 1, (3, 3))

array([[ 0.21194971,  2.51718004,  1.02107651],
       [-1.28534424,  0.44575877,  1.4112015 ],
       [ 0.1189625 , -1.68291529, -0.45390421]])

In [ ]:
#### 创建一个3*3的、[0, 10]区间的随机整型数组

In [25]:
np.random.randint(0, 10, (3, 3))

array([[1, 7, 6],
       [6, 1, 1],
       [6, 5, 0]])

In [ ]:
#### 创建一个3*3的单位矩阵

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#### 创建一个由3个整型数组成的未初始化的数组

In [27]:
# 数组的值是内存空间中的任意值
np.empty(3)

array([1., 1., 1.])

In [ ]:
## NumPy标准数据类型

    
        +------------------+-------------------------------------------------------------------+
        |  数据类型         |    描述                                                           |
        +------------------+-------------------------------------------------------------------+
        |1.bool_           | 布尔值（真、True或假、False），用一个字节存储                        |
        +------------------+-------------------------------------------------------------------+
        | 2.int_           | 默认整型（类似于C语言中的long, 通常情况下是Int64或int32）             |
        +------------------+-------------------------------------------------------------------+
        | 3.intc           | 同C语言的int相同（通常是int32或int64）                              |
        +------------------+-------------------------------------------------------------------+
        | 4.intp           | 用作索引的整型（和C语言的ssize_t相同，通常情况下是int32或int64）      |
        +------------------+-------------------------------------------------------------------+
        | 5.int8           | 字节（byte, 范围从-128到127）                                       |
        +------------------+-------------------------------------------------------------------+
        | 6.int16          | 整型（范围从-32768到32767）                                         |
        +------------------+-------------------------------------------------------------------+
        | 7.int32          | 整型（范围从-2147483648到2147483647）                               |
        +------------------+-------------------------------------------------------------------+
        | 8.int64          | 整型（范围从-9223372036854775808到9223372036854775807）             |
        +------------------+-------------------------------------------------------------------+
        | 9.uint8          | 无符号整型（范围从0到255）                                          |
        +------------------+-------------------------------------------------------------------+
        | 10.uint16        | 无符号整型（范围从0到65535）                                        |
        +------------------+-------------------------------------------------------------------+
        | 11.uint32        | 无符号整型（范围从0到4294967295）                                   |
        +------------------+-------------------------------------------------------------------+
        | 12.uint64        | 无符号整型（范围从0到18446744073709551615）                         |
        +------------------+-------------------------------------------------------------------+
        | 13.float_        | float64的简化形式                                                  |
        +------------------+-------------------------------------------------------------------+
        | 14.float16       | 半精度浮点型：符号比特位，5比特位指数（exponent），10比特位尾数        |
        +------------------+-------------------------------------------------------------------+
        | 15.float32       | 单精度浮点型：符号比特位，8比特位指数，23比特位尾数                    |
        +------------------+-------------------------------------------------------------------+
        | 16.float64       | 双精度浮点型：符号比特位，11比特位指数，52比特位尾数                  |
        +------------------+-------------------------------------------------------------------+
        | 17.complex_      | complex128的简化形式                                               |
        +------------------+-------------------------------------------------------------------+
        | 18.complex64     | 复数，由两个32位浮点数表示                                          |
        +------------------+-------------------------------------------------------------------+
        | 19.complex128    | 复数，由两个64位浮点数表示                                          |
        +------------------+-------------------------------------------------------------------+
        
       

In [ ]:
## NumPy数组基础
- 数组的属性
确定数组的大小、形状、存储大小、数据类型。
- 数组的索引
获取和设置数组各个元素的值。
- 数组的切分
在大的数组中获取或设置更小的子树组。
- 数组的变形
改变给定数组的形状。
- 数组的拼接和分裂
将多个数组合并为一个，以及将一个数组分裂成多个。

In [ ]:
### NumPy数组的属性

In [ ]:
我们将用NumPy的随机生成器设置一组种子值，以确保每次 程序执行时都可以生成同样的随机数组

In [30]:
import numpy as np
np.random.seed(0)     # 设置随机数种子

x1 = np.random.randint(10, size=6)    # 一维数组
x2 = np.random.randint(10, size=(3, 4))    # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5))    # 三维数组


In [ ]:
每个数组有：
- ndim:数组的维度
- shape: 数组每个维度的大小
- size: 数组的总大小

In [31]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [32]:
print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12


In [33]:
print("x1 ndim: ", x2.ndim)
print("x1 shape: ", x2.shape)
print("x2 size: ", x2.size)

x1 ndim:  2
x1 shape:  (3, 4)
x2 size:  12


In [ ]:
另外一个有用的属性是dtype，它是数组的数据类型

In [34]:
print("dtype: ", x3.dtype)

dtype:  int32


In [ ]:
其他的属性包括表示每个数组元素字节大小的itemsize，以及表示数组总字节大小的属性nbytes:

In [35]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [ ]:
### 数组索引：获取单个元素

In [ ]:
和python列表一样，在一维数组中，你也可以通过中括号指定索引获取第i个值（从0开始计数）：

In [36]:
x1

array([5, 0, 3, 3, 7, 9])

In [37]:
x1[0]

5

In [38]:
x1[4]

7

In [ ]:
为了获取数组的末尾索引，可以用负值索引：

In [39]:
x1[-1]

9

In [40]:
x1[-2]

7

In [ ]:
在多维数组中，可以用逗号分隔的索引元组获取元素：

In [41]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [42]:
x2[0, 0]

3

In [43]:
x2[2, 0]

1

In [44]:
x2[2, -1]

7

In [ ]:
也可以用以上索引方式修改元素值：

In [45]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
和python列表不同，NumPy数组是固定类型的。这意味着当你试图将一个浮点值插入一个整形数组时，浮点值会被截短成整型。并且这种截短是自动完成的，不会给你任何提示
或警告。

In [48]:
x1[0] = 3.14159262758 # 这将被截短
x1

array([3, 0, 3, 3, 7, 9])

In [ ]:
## 数组切片
- 我们可以用切片(slice)符号获取子数组，切片符号用冒号（:）表示。
- 为了获取数组的一个切片，可以使用 x[start:stop:step]    

In [ ]:
#### 一维数组

In [49]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
x[:5]     # 获取前5个元素


array([0, 1, 2, 3, 4])

In [51]:
x[5:]     # 获取索引5之后的元素

array([5, 6, 7, 8, 9])

In [52]:
x[4:7]    # 获取4~7之间的元素

array([4, 5, 6])

In [53]:
x[::2]    # 每隔一个元素

array([0, 2, 4, 6, 8])

In [54]:
x[::3]    # 每隔3个元素

array([0, 3, 6, 9])

In [55]:
x[::5]    # 每隔5个元素

array([0, 5])

In [56]:
x[1::2]     # 每隔一个元素，从索引1开始

array([1, 3, 5, 7, 9])

In [57]:
x[::-1]     # 所有元素，逆序的

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [58]:
x[5::-2]    # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

In [ ]:
#### 多维子数组
多维子数组也采用同样的方式处理，用逗号分隔。

In [59]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [60]:
x2[:2, :3]    # 两行，三列

array([[12,  5,  2],
       [ 7,  6,  8]])

In [61]:
x2[:3, ::2]    # 所有行，每隔一列

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [ ]:
子数组维度也可以同时被逆序

In [62]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [ ]:
#### 获取数组的行和列
一种常见的需求是获取数组的单行和单列，可以将索引与切片组合起来实现这个功能，用一个冒号(:)表示空切片：

In [63]:
print(x2[:, 0])    # x2的第一列

[12  7  1]


In [64]:
print(x2[0, :])    # x2的第一行

[12  5  2  4]


In [65]:
print(x2[0])    # 等于x2[0, :]

[12  5  2  4]


In [ ]:
#### 非副本视图的子数组
关于数组切片有一点很重要也非常有用，那就是数组切片返回的是数组数据的视图，而不是数值数据的副本。

In [66]:
# 此前示例中的那个二维数组
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
从中抽取一个2*2的子数组：

In [68]:
x2_sub =  x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [ ]:
如果修改这个子数组，将会看到原始数组也被修改了：

In [69]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [ ]:
#### 创建数组的副本
尽管数组视图有一些非常好的特性，但是在有些时候明确地复制数组里的数据或子数组是非常有用的，可以很简单地通过copy()方法实现：

In [70]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [ ]:
如果这个时候修改这个子数组，原始的数组不会被改变：

In [71]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [72]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
### 数组的变形
另一个有用的操作数据类型是数组的变形。数组变形最灵活的实现方式是通过reshape()函数来实现。

In [ ]:
例如，如果你希望数字1~9放入一个3*3的矩阵中，可以采用如下方法：

In [4]:
import numpy as np
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
另一个常见的变形模式是将一个一维数组转变为二维的行或列的矩阵。可以通过reshape()方法实现，或者更简单地在一个切片操作中利用newaxis关键字：

In [2]:
x = np.array([1, 2, 3])

# 通过变形获得的行向量
x.reshape((1, 3))

array([[1, 2, 3]])

In [ ]:
通过newaxis获得的行向量

In [3]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
通过变形获得的列向量

In [6]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
通过newaxis获得的列向量

In [7]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
### 数组拼接和分裂
- 数组的拼接
- 数组的分裂
以上所有的操作都是针对单一数组的，但有时也需要将多个数组合并为一个，或将一个数组分裂成多个。

In [ ]:
#### 数组的拼接
- 拼接或连接Numpy中的两个数组主要由np.concatenate、np.vstack和np.hstack例程实现。
- np.concatenate将数组元组或数组列表作为第一个参数，如下所示：

In [8]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
也可以一次性拼接两个以上数组：

In [9]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [ ]:
np.concatenate也可以用于二维数组的拼接：

In [ ]:
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])



In [ ]:
沿着第一个轴拼接

In [10]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
沿着第二个轴拼接（从0开始索引）

In [11]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
沿着固定维度处理数组时，使用np.vstack(垂直栈)和np.hstack(水平栈)函数会更简洁：

In [12]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], 
                 [6, 5, 4]])

# 垂直栈数组
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
水平栈数组

In [13]:
y = np.array([[99], 
              [99]])

np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
#### 数组的分裂
- 与拼接相反的过程是分裂。
- 分裂可以通过np.split、np.hsplit和np.vsplit函数来实现。

In [ ]:
可以向上函数传递一个索引作为参数，索引列表记录的是分裂点位置：

In [14]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
N分裂点会得到N+1个子数组。相关的np.hsplit和np.vsplit的用法也类似：

In [15]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
grid = np.arange(100).reshape((10, 10))
grid

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [18]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [10 11]
 [20 21]
 [30 31]
 [40 41]
 [50 51]
 [60 61]
 [70 71]
 [80 81]
 [90 91]]
[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]
 [22 23 24 25 26 27 28 29]
 [32 33 34 35 36 37 38 39]
 [42 43 44 45 46 47 48 49]
 [52 53 54 55 56 57 58 59]
 [62 63 64 65 66 67 68 69]
 [72 73 74 75 76 77 78 79]
 [82 83 84 85 86 87 88 89]
 [92 93 94 95 96 97 98 99]]


In [ ]:
同样，np.dsplit将数组沿着第三个维度分裂

In [19]:
## NumPy数组的计算：通用函数

In [ ]:
### 缓慢的循环

In [21]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [ ]:
我们还可以利用ipython的%timeit魔法函数来测量：

In [22]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.14 s ± 55.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
### 通用函数介绍

In [ ]:
比较以下两个结果：

In [23]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [ ]:
如果计算一个较大数组的运行时间，可以看到它的完成时间比python循环花费的时间更短：

In [24]:
%timeit (1.0 / big_array)

5.36 ms ± 198 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
也可以对两个数组进行运算：

In [25]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
通用函数并不仅限于一维数组的运算，它们也可以进行多维数组的运算：

In [26]:
x = np.arange(9).reshape((3, 3))
2 ** x 

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [ ]:
### 探索NumPy的通用函数
通用函数有两种存在形式：
- 一元通用函数(unary ufunc):对单个输入操作；
- 二元通用函数(binary ufunc): 对两个输入操作。

In [ ]:
#### 数组的运算
NumPy通用函数的使用方式非常自然，因为它用到了Python原生的算术运算符，标准的加、减、乘、除都可以使用：

In [27]:
x = np.arange(4)
print("x     ", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)     # 向下整除运算


x      [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [ ]:
还有求负数，**表示的指数运算符和%表示的模运算符的一元通用函数：

In [28]:
print("-x     =", -x)
print("x **2  =", x ** 2)
print("x % 2  =", x % 2)

-x     = [ 0 -1 -2 -3]
x **2  = [0 1 4 9]
x % 2  = [0 1 0 1]


In [ ]:
你可以任意将这些算术运算符组合使用。当然，你得考虑这些运算符的优先级：

In [29]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [ ]:
所有这些算术运算符都是NumPy内置函数的简单封装器，例如+运算符就是一个add函数的封装器：

In [31]:
np.add(x, 2)

array([2, 3, 4, 5])

In [ ]:
NumPy实现的算术运算符

In [ ]:
         
        +-------------+--------------------------+-------------------------------------------------+
        | 运算符       |  对应的通用函数           |  描述                                           |
        +-------------+--------------------------+-------------------------------------------------+
        |    +        |  np.add                  |  加法运算（即 1 + 1 = 2）                        |
        +-------------+--------------------------+-------------------------------------------------+
        |    -        |  np.subtract             |  减法运算（即 3 - 2 = 1）                        |
        +-------------+--------------------------+-------------------------------------------------+
        |    -        | np.negative              |  负数运算（即-2）                                |
        +-------------+--------------------------+-------------------------------------------------+
        |    *        | np.multiply              |  乘法运算（即 2 * 3 = 6）                        |
        +-------------+--------------------------+-------------------------------------------------+
        |    /        | np.divide                |  除法运算（即 3 / 2 = 1.5）                      |
        +-------------+--------------------------+-------------------------------------------------+
        |   //        |  np.floor_divide         |  向下整除运算（floor division, 即 3 // 2 = 1）    |
        +-------------+--------------------------+-------------------------------------------------+
        |   **        |  np.power                |  指数运算（即 2 ** 3 = 8）                       |
        +-------------+--------------------------+-------------------------------------------------+
        |   %         |  np.mod                  |   模/余数（即 9 % 4 = 1）                        |
        +-------------+--------------------------+-------------------------------------------------+
        
        另外，NumPy还有布尔/位运算。
    

In [ ]:
#### 绝对值
NumPy也可以理解Python内置的绝对值函数：

In [32]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [ ]:
对应的NumPy通用函数是np.absolute,该函数也可以用别名np.abs来访问：

In [33]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [34]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [35]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [ ]:
#### 三角函数
NumPy提供了大量好用的通用函数，其中对数据科学家最有用的就是三角函数。

In [ ]:
首先定义一个角度数组：

In [ ]:
theta = np.linspace(0, np.pi, 3)

In [ ]:
现在可以对这些值进行一些三角函数计算：

In [ ]:
print("theta      = ", theta)
print("sin(theta) = ",  np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))



In [ ]:
## 数组拼接和分裂
以上所有的操作都是针对单一数组的，但有时也需要将多个数组合并为一个，或将一个数组分裂成多个。

In [ ]:
### 数组的拼接
拼接或连接NumPy中的两个数组主要是由np.concatenate、np.vstack和np.hstack例程实现。np.concatenate将数组元组或数组列表作为第一个参数：

In [2]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
也可以一次性拼接两个以上数组

In [3]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [4]:
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])

# 沿着第一个轴拼接
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
# 沿着第二个轴拼接（从0开始索引）
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [7]:
# 沿着固定维度处理数组时，使用np.vstack(垂直栈)和np.hstack(水平线)函数会更简洁
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], 
                 [6, 5, 4]])

# 垂直栈数组
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [8]:
# 水平栈数组
y = np.array([[99], 
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
### 数组的分裂