In [1]:
import numpy as np
import pandas as pd

# use pandas to extract rainfall inches as a NumPy array
rainfall = pd.read_csv('D:\Coding\Coding\1.Python-learning\Python-Excel\Packages\Python-Data-Science\data\Seattle2014.csv')['PRCP'].values
inches = rainfall / 254.0    # 1/10mm -> inches
inches.shape

FileNotFoundError: File b'D:\\Coding\\Coding\x01.Python-learning\\Python-Excel\\Packages\\Python-Data-Science\\data\\Seattle2014.csv' does not exist

In [4]:
%debug

> d:\coding\coding\1.python-learning\python-excel\packages\python-data-science\numpy\pandas\_libs\parsers.pyx(695)pandas._libs.parsers.TextReader._setup_parser_source()

ipdb> quit


The array contains 365 values, giving daily rainfall in inches from January 1 to December 31, 2014.

As a first quick visualization, let`s look at the histogram of rainy days, which was generated
using Matplotlib (we will explore this tool more fully in [Chapter 4](04.00-Introduction-To-Matplotlib.ipynb)):

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()     # set plot styles

In [2]:
plt.hist(inches, 40)

NameError: name 'inches' is not defined

In [5]:
%debug

> d:\coding\coding\1.python-learning\python-excel\packages\python-data-science\numpy\pandas\_libs\parsers.pyx(695)pandas._libs.parsers.TextReader._setup_parser_source()

ipdb> quit


In [ ]:
The histogram gives us a general idea of what the data looks like: despite its reputation
, the vast majority of days in Seattle saw near zero measured rainfall in 2014.But this
doesn`t do a good job of converying some information we`d like to see:
for example, how many rainy days were there in the year? What is the average precipitation
on those rainy days? How many days were there with more than half an inch of rain?

In [ ]:
Digging into the data

One approach to this would be to answer these questions by hand: loop through the data, 
incrementing a counter each time we see values in some desired range.For reasons discussed
throughout this chapter, such an approach is very inefficient, both from the standpoint
of time writing code and time computing the result.We saw in Computation on NumPy Arrays:
Universal Functions that NumPy`s ufuncs can be used in place of loops to do fast element-wise
arithmetic operations on arrays; in the same way, we can use other ufuncs to do element-wise comparisons
over arrays, and we can then manipulate the results to answer the questions we have. We`ll
leave the data asider for right now, and discuss some general tools in NumPy to use masking
to quickly answer these types of questions.

In [ ]:
## Comparison Operators as ufuncs

In [ ]:
In Computation on NumPy Arrays: Universal Functions we introduced ufuncs, and focused
in particular on arithmetic operators. We saw that using +, -, *, /, and others on arrays
leads to element-wise operations.NumPy also implements comparison operators such as <(less than) and
> (greater than) as element-wise ufuncs.The result of these comparison operators is always a Boolean
data type.All six of the standard comparison operations are available:

In [6]:
x = np.array([1, 2, 3, 4, 5])

In [7]:
# less than
x < 3  

array([ True,  True, False, False, False])

In [8]:
# greater than
x > 3 

array([False, False, False,  True,  True])

In [9]:
# less than or equal
x <= 3

array([ True,  True,  True, False, False])

In [10]:
# greater than or equal
x >= 3

array([False, False,  True,  True,  True])

In [11]:
# not equal
x != 3 

array([ True,  True, False,  True,  True])

In [12]:
# equal
x == 3

array([False, False,  True, False, False])

In [ ]:
### It is also possible to do an element-wise comparison of two arrays, and to do include
compound expressions:

In [13]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [ ]:
Just as in the case of arithmetic ufuncs, these will work on arrays of any size and shape.
Here is a two-dimensional example:

In [14]:
rng = np.random.RandomState(0)
x = rng.randint(10, size = (3, 4))
x 

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [15]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [ ]:
## Working with Boolean Arrays

In [ ]:
Given a Boolean array, there are a host of useful operations you can do. We`ll work with
x, the two-dimensional array we created earlier.

In [16]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [ ]:
### Counting entries

In [ ]:
To count the number of True entries in a Boolean array, np.count_nonzero is useful:

In [ ]:
# how many values less than 6?
np.count_nonzero(x < 6)

In [ ]:
We see that are eight array entries that are less than 6.Anoter way to get at this information is to use np.sum;
in this case, False is interpreted as 0, and True is interpreted as 1:

In [17]:
np.sum(x < 6)

8